### PR TITLE
return ID on create

### PR DESCRIPTION
**Pull request by xh3b4sd**
This aligns the API with the recent changes.

See also 
- https://github.com/giantswarm/api/pull/222
- https://github.com/giantswarm/cluster-client/pull/2
- https://github.com/giantswarm/cluster-service/pull/4

RFR @marians @oponder @JosephSalisbury

### CODE REVIEW

**Comment by oponder** [comment]
LGTM! Thx @xh3b4sd

**Comment by marians** [comment]
@oponder Are you doing the follow-up change here in JS?

**Comment by oponder** [comment]
In js-client ? this is for the admin call... passage makes this call right?

Happa will iterate over the list of orgs and find the last created cluster as discussed right?

**Comment by oponder** [comment]
@marian: actually passage doesn't make this request. 
this is a request that happens way at the start of the process, done by an admin. We haven't mocked this at all yet. Do we want it mocked?

**Comment by marians** [comment]
Good point. No need to mock it.

**Comment by xh3b4sd** [comment]
Not sure about your discussion and status, but if you guys don't mind I am going to merge this PR together with the other ones when they are ready.

**Comment by oponder** [comment]
yup, go ahead and merge when you feel like it

**Pull request merged**
