### PR TITLE
More cluster api

### PR DESCRIPTION
**Pull request by marians**
@oponder Ready for review

### CODE REVIEW

**Comment by oponder** [comment]
@marian: where do we get <CA_DATA> from? Is that going to be the same for all clusters?

```
apiVersion: v1
kind: Config
clusters:
 - cluster:
     certificate-authority-data: <CA_DATA>
     server: https://go9cdgqfnr.giantswarm-kaas.io
   name: go9cdgqfnr
contexts:
 - context:
     cluster: go9cdgqfnr
     user: giantswarm-default-admin
   name: giantswarm-default
users:
 - name: giantswarm-default-admin
   user:
     client-certificate-data: <CLIENT_CERTIFICATE_DATA>
     client-key-data: <CLIENT_KEY_DATA>
```

**Comment by oponder** [comment]
Also miss the call to get a list of all clusters belonging to a organisation. As far as I know, Happa won't have a way otherwise of knowing the user's cluster id. 

/v3/orgs/:orgname/clusters/  (to get all clusters belonging to a user's organisation)

**Comment by marians** [comment]
> where do we get <CA_DATA>

Good point. Yes, I'm assuming this is the same for all clusters, but we need to address this.

> _listing clusters missing_

Ehm, yes. Will add that.

**Comment by marians** [comment]
Ready for another look ;-)

**Comment by oponder** [comment]
Thanks!

I noticed you gave the org two clusters, (`other_cluster_id`) and it is the first one which means a naive Happa would try to pick `other_cluster_id` to show details about in the getting started docs.

So that brings to question: how will happa know which orgs have clusters, and which is relevant to show during the getting started.

Should it do a iteration of all the organisations that a user belongs to and try to find any that have clusters, and then just show the first one?

I think we either need to already think of a very minimal way to let users know what they're looking at and to switch between org and cluster, or agree that only the first cluster that Happa finds will be queried and shown on the getting started docs, in which case we have to change the mock api to either: have data for `other_cluster_id` or only have one cluster for the org.

**Comment by marians** [comment]
As long as there is no cluster selection, happa should only present the newest of the clusters.

**Comment by oponder** [comment]
:+1: that clears it up :)

LGTM!

**Comment by marians** [comment]
> Should it do a iteration of all the organisations that a user belongs to and try to find any that have clusters, and then just show the first one?

Yeah. Iterating all orgs is necessary. I guess I'll have to modify the `/v3/orgs/:org/clusters/` response to return empty lists for all except `validorg`.

**Comment by oponder** [comment]
I can gracefully deal with the 404 also in the js-client

**Comment by marians** [comment]
Added the empty list response. Handling a 404 would be fine in addition.

**Comment by oponder** [comment]
👍 lgtm

**Pull request merged**
